_controllers:
  resource: '../src/Controller/'
  type: attribute

when@dev:
  _profiler:
    resource: '@WebProfilerBundle/Resources/config/routing/wdt.xml'
    prefix: /_wdt

  _profiler_router:
    resource: '@WebProfilerBundle/Resources/config/routing/profiler.xml'
    prefix: /_profiler
